from app.core.enums import PriorityEnum, RenderType
from app.core.slot_contracts import SECTION_EXPECTED_KPIS, SECTION_SLOT_CONTRACTS


SECTION_REGISTRY = [
    {
        "section_id": "cover",
        "display_name": "Couverture",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "cover_hero_stats_v1",
        "component_fallback": "cover_simple_title_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["cover"],
        "expected_kpis": SECTION_EXPECTED_KPIS["cover"],
    },
    {
        "section_id": "executive_summary",
        "display_name": "Synthèse exécutive",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "dashboard_kpi_v1",
        "component_fallback": "summary_table_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["executive_summary"],
        "expected_kpis": SECTION_EXPECTED_KPIS["executive_summary"],
    },
    {
        "section_id": "methodology_sources",
        "display_name": "Méthodologie & sources",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "sources_grid_v1",
        "component_fallback": "summary_table_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["methodology_sources"],
        "expected_kpis": SECTION_EXPECTED_KPIS["methodology_sources"],
    },
    {
        "section_id": "market_scorecard",
        "display_name": "Scorecard marché",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "score_dashboard_7_v1",
        "component_fallback": "summary_table_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["market_scorecard"],
        "expected_kpis": SECTION_EXPECTED_KPIS["market_scorecard"],
    },
    {
        "section_id": "demographics",
        "display_name": "Démographie",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "dual_chart_demography_v1",
        "component_fallback": "multi_zone_compare_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["demographics"],
        "expected_kpis": SECTION_EXPECTED_KPIS["demographics"],
    },
    {
        "section_id": "target_segments",
        "display_name": "Seniors & segments cibles",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "segment_mix_cards_v1",
        "component_fallback": "quote_fact_box_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["target_segments"],
        "expected_kpis": SECTION_EXPECTED_KPIS["target_segments"],
    },
    {
        "section_id": "employment_talent",
        "display_name": "Emploi & vivier RH",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "rh_dashboard_v1",
        "component_fallback": "summary_table_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["employment_talent"],
        "expected_kpis": SECTION_EXPECTED_KPIS["employment_talent"],
    },
    {
        "section_id": "income_housing",
        "display_name": "Économie, revenus & habitat",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "income_housing_dual_v1",
        "component_fallback": "multi_zone_compare_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["income_housing"],
        "expected_kpis": SECTION_EXPECTED_KPIS["income_housing"],
    },
    {
        "section_id": "real_estate",
        "display_name": "Immobilier (prix m² / loyer)",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "real_estate_dashboard_v1",
        "component_fallback": "summary_table_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["real_estate"],
        "expected_kpis": SECTION_EXPECTED_KPIS["real_estate"],
    },
    {
        "section_id": "microzones",
        "display_name": "Quartiers, rues & routes",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "microzones_map_table_v1",
        "component_fallback": "summary_table_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["microzones"],
        "expected_kpis": SECTION_EXPECTED_KPIS["microzones"],
    },
    {
        "section_id": "competition_mapping",
        "display_name": "Concurrence",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "competition_dense_table_v1",
        "component_fallback": "battlecard_top5_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["competition_mapping"],
        "expected_kpis": SECTION_EXPECTED_KPIS["competition_mapping"],
    },
    {
        "section_id": "regulation_feasibility",
        "display_name": "Réglementation & faisabilité",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "regulation_focus_v1",
        "component_fallback": "summary_table_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["regulation_feasibility"],
        "expected_kpis": SECTION_EXPECTED_KPIS["regulation_feasibility"],
    },
    {
        "section_id": "swot",
        "display_name": "SWOT",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "swot_quadrants_v1",
        "component_fallback": "swot_table_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["swot"],
        "expected_kpis": SECTION_EXPECTED_KPIS["swot"],
    },
    {
        "section_id": "verdict",
        "display_name": "Verdict",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "verdict_card_v1",
        "component_fallback": "quote_fact_box_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["verdict"],
        "expected_kpis": SECTION_EXPECTED_KPIS["verdict"],
    },
    {
        "section_id": "action_plan",
        "display_name": "Plan d'action",
        "priority": PriorityEnum.P0,
        "required": True,
        "component_main": "action_plan_timeline_v1",
        "component_fallback": "summary_table_v1",
        "render_types": [RenderType.HTML, RenderType.PPTX],
        "slot_contract": SECTION_SLOT_CONTRACTS["action_plan"],
        "expected_kpis": SECTION_EXPECTED_KPIS["action_plan"],
    },
]
