SOURCE_REGISTRY = [
    {
        "country": "FR",
        "theme_id": "demography",
        "source_name": "INSEE",
        "priority_order": 1,
        "source_type": "official_national",
    },
    {
        "country": "FR",
        "theme_id": "target_segments",
        "source_name": "INSEE",
        "priority_order": 1,
        "source_type": "official_national",
    },
    {
        "country": "FR",
        "theme_id": "employment",
        "source_name": "France Travail",
        "priority_order": 1,
        "source_type": "semi_official",
    },
    {
        "country": "FR",
        "theme_id": "income_housing",
        "source_name": "INSEE",
        "priority_order": 1,
        "source_type": "official_national",
    },
    {
        "country": "FR",
        "theme_id": "competition",
        "source_name": "Google Maps",
        "priority_order": 1,
        "source_type": "commercial",
    },
    {
        "country": "FR",
        "theme_id": "competition",
        "source_name": "Pages Jaunes",
        "priority_order": 2,
        "source_type": "commercial",
    },
    {
        "country": "FR",
        "theme_id": "regulation",
        "source_name": "service-public.fr",
        "priority_order": 1,
        "source_type": "official_national",
    },
    {
        "country": "FR",
        "theme_id": "regulation",
        "source_name": "URSSAF",
        "priority_order": 2,
        "source_type": "official_national",
    },
    {
        "country": "ES",
        "theme_id": "demography",
        "source_name": "INE",
        "priority_order": 1,
        "source_type": "official_national",
    },
    {
        "country": "ES",
        "theme_id": "target_segments",
        "source_name": "INE",
        "priority_order": 1,
        "source_type": "official_national",
    },
    {
        "country": "ES",
        "theme_id": "employment",
        "source_name": "SEPE",
        "priority_order": 1,
        "source_type": "official_national",
    },
    {
        "country": "ES",
        "theme_id": "income_housing",
        "source_name": "INE",
        "priority_order": 1,
        "source_type": "official_national",
    },
    {
        "country": "ES",
        "theme_id": "competition",
        "source_name": "Google Maps",
        "priority_order": 1,
        "source_type": "commercial",
    },
    {
        "country": "ES",
        "theme_id": "competition",
        "source_name": "annuaires locaux",
        "priority_order": 2,
        "source_type": "commercial",
    },
    {
        "country": "ES",
        "theme_id": "regulation",
        "source_name": "BOE",
        "priority_order": 1,
        "source_type": "official_national",
    },
    {
        "country": "ES",
        "theme_id": "regulation",
        "source_name": "comunidad autónoma",
        "priority_order": 2,
        "source_type": "official_regional",
    },
]
