KPI_CATALOG = [
    # === DEMOGRAPHY ===
    {"metric_id": "population_total", "theme_id": "demography", "label": "Population totale", "unit": "habitants", "priority": "P0",
     "description": "Taille de marché locale de base.",
     "source_priority": ["official_national", "official_regional", "official_local"]},
    {"metric_id": "population_growth_5y", "theme_id": "demography", "label": "Croissance population 5 ans", "unit": "%", "priority": "P1",
     "description": "Dynamisme territorial récent.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "density_population", "theme_id": "demography", "label": "Densité de population", "unit": "hab/km²", "priority": "P1",
     "description": "Densité commerciale et efficacité opérationnelle.",
     "source_priority": ["official_national", "official_regional"]},

    # === TARGET SEGMENTS ===
    {"metric_id": "seniors_60_plus_share", "theme_id": "target_segments", "label": "Part des 60 ans et plus", "unit": "%", "priority": "P0",
     "description": "Cœur de cible aide à domicile.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "seniors_75_plus_share", "theme_id": "target_segments", "label": "Part des 75 ans et plus", "unit": "%", "priority": "P0",
     "description": "Proxy de dépendance et aide renforcée.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "single_senior_households", "theme_id": "target_segments", "label": "Ménages seniors seuls", "unit": "ménages", "priority": "P1",
     "description": "Usage récurrent fort des services à domicile.",
     "source_priority": ["official_national", "official_regional", "official_local"]},
    {"metric_id": "households_with_children_share", "theme_id": "target_segments", "label": "Ménages avec enfants", "unit": "%", "priority": "P0",
     "description": "Potentiel garde et ménage famille.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "working_age_women_share", "theme_id": "target_segments", "label": "Femmes 25-54 ans", "unit": "%", "priority": "P1",
     "description": "Signal de demande famille / externalisation.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "dependency_ratio_apa", "theme_id": "target_segments", "label": "Bénéficiaires APA estimés", "unit": "personnes", "priority": "P0",
     "description": "Demande directe pour aide à domicile dépendance.",
     "source_priority": ["official_regional", "official_local"]},

    # === EMPLOYMENT ===
    {"metric_id": "unemployment_rate", "theme_id": "employment", "label": "Taux de chômage", "unit": "%", "priority": "P0",
     "description": "Mesure du vivier RH local.",
     "source_priority": ["official_national", "official_regional", "semi_official"]},
    {"metric_id": "care_worker_pool", "theme_id": "employment", "label": "Vivier care/services", "unit": "personnes", "priority": "P0",
     "description": "Profils mobilisables pour services à domicile.",
     "source_priority": ["official_national", "official_regional", "semi_official"]},
    {"metric_id": "jobseekers_service_sector", "theme_id": "employment", "label": "Demandeurs d'emploi services", "unit": "personnes", "priority": "P1",
     "description": "Disponibilité de recrutement rapide.",
     "source_priority": ["official_national", "official_regional", "semi_official"]},

    # === INCOME & HOUSING (general) ===
    {"metric_id": "median_income", "theme_id": "income_housing", "label": "Revenu médian", "unit": "EUR", "priority": "P0",
     "description": "Capacité de paiement.",
     "source_priority": ["official_national", "official_regional", "semi_official"]},
    {"metric_id": "taxable_households_share", "theme_id": "income_housing", "label": "Ménages imposables", "unit": "%", "priority": "P1",
     "description": "Solvabilité et élasticité premium.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "home_ownership_share", "theme_id": "income_housing", "label": "Propriétaires occupants", "unit": "%", "priority": "P1",
     "description": "Stabilité résidentielle et récurrence.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "tenants_share", "theme_id": "income_housing", "label": "Locataires", "unit": "%", "priority": "P1",
     "description": "Dichotomie propriétaires/locataires - signal segmentation.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "secondary_residences_share", "theme_id": "income_housing", "label": "Résidences secondaires", "unit": "%", "priority": "P1",
     "description": "Ménage ponctuel, conciergerie, saisonnalité.",
     "source_priority": ["official_national", "official_regional", "official_local"]},
    {"metric_id": "vacant_housing_share", "theme_id": "income_housing", "label": "Logements vacants", "unit": "%", "priority": "P2",
     "description": "Indicateur de tension immobilière.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "houses_vs_apartments_share", "theme_id": "income_housing", "label": "Part maisons vs appartements", "unit": "%", "priority": "P1",
     "description": "Typologie logements - impact services jardinage/ménage.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "avg_house_surface", "theme_id": "income_housing", "label": "Surface moyenne maisons", "unit": "m²", "priority": "P1",
     "description": "Volume de ménage par intervention.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "avg_apartment_surface", "theme_id": "income_housing", "label": "Surface moyenne appartements", "unit": "m²", "priority": "P2",
     "description": "Volume ménage urbain par intervention.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "avg_land_surface", "theme_id": "income_housing", "label": "Surface moyenne terrain", "unit": "m²", "priority": "P2",
     "description": "Potentiel jardinage et entretien extérieur.",
     "source_priority": ["official_national", "official_regional"]},

    # === REAL ESTATE PRICES (proxy solvabilité majeur) ===
    {"metric_id": "real_estate_price_house_m2", "theme_id": "real_estate", "label": "Prix maisons au m²", "unit": "EUR/m²", "priority": "P0",
     "description": "Proxy direct de richesse / solvabilité du territoire.",
     "source_priority": ["official_national", "commercial"]},
    {"metric_id": "real_estate_price_apartment_m2", "theme_id": "real_estate", "label": "Prix appartements au m²", "unit": "EUR/m²", "priority": "P0",
     "description": "Proxy de richesse urbaine.",
     "source_priority": ["official_national", "commercial"]},
    {"metric_id": "real_estate_avg_transaction", "theme_id": "real_estate", "label": "Prix moyen transaction", "unit": "EUR", "priority": "P1",
     "description": "Valeur moyenne biens vendus.",
     "source_priority": ["official_national", "commercial"]},
    {"metric_id": "rental_price_m2", "theme_id": "real_estate", "label": "Loyer moyen au m²", "unit": "EUR/m²/mois", "priority": "P0",
     "description": "Plus le loyer est élevé, plus la zone est solvable.",
     "source_priority": ["official_national", "commercial"]},
    {"metric_id": "real_estate_price_growth_5y", "theme_id": "real_estate", "label": "Évolution prix immo 5 ans", "unit": "%", "priority": "P1",
     "description": "Dynamique de valorisation du territoire.",
     "source_priority": ["official_national", "commercial"]},
    {"metric_id": "real_estate_premium_zone_share", "theme_id": "real_estate", "label": "Part zones premium dans périmètre", "unit": "%", "priority": "P0",
     "description": "Part du périmètre où prix m² > seuil premium.",
     "source_priority": ["official_national", "commercial"]},

    # === MICROZONES (quartier / rue / route) ===
    {"metric_id": "neighborhood_count", "theme_id": "microzones", "label": "Nombre de quartiers analysés", "unit": "quartiers", "priority": "P0",
     "description": "Granularité fine du périmètre.",
     "source_priority": ["official_national", "official_local"]},
    {"metric_id": "premium_neighborhoods_count", "theme_id": "microzones", "label": "Quartiers premium identifiés", "unit": "quartiers", "priority": "P0",
     "description": "Quartiers à fort potentiel solvabilité.",
     "source_priority": ["official_national", "commercial"]},
    {"metric_id": "key_streets_count", "theme_id": "microzones", "label": "Rues clés ciblées", "unit": "rues", "priority": "P1",
     "description": "Rues à forte densité de cibles.",
     "source_priority": ["official_local", "commercial"]},
    {"metric_id": "main_traffic_axes", "theme_id": "microzones", "label": "Axes routiers structurants", "unit": "axes", "priority": "P1",
     "description": "Routes structurantes du périmètre d'intervention.",
     "source_priority": ["official_local"]},
    {"metric_id": "transit_lines_count", "theme_id": "microzones", "label": "Lignes transports en commun", "unit": "lignes", "priority": "P2",
     "description": "Mobilité collective intervenants.",
     "source_priority": ["official_local"]},

    # === COMPETITION ===
    {"metric_id": "competitor_count_15min", "theme_id": "competition", "label": "Concurrents dans 15 min", "unit": "acteurs", "priority": "P0",
     "description": "Pression concurrentielle immédiate.",
     "source_priority": ["commercial", "corporate", "semi_official"]},
    {"metric_id": "competitor_count_30min", "theme_id": "competition", "label": "Concurrents dans 30 min", "unit": "acteurs", "priority": "P1",
     "description": "Pression concurrentielle élargie.",
     "source_priority": ["commercial", "corporate"]},
    {"metric_id": "top_competitor_density", "theme_id": "competition", "label": "Densité top concurrents", "unit": "indice", "priority": "P0",
     "description": "Concentration de leaders visibles.",
     "source_priority": ["commercial", "corporate"]},
    {"metric_id": "brand_presence_flag", "theme_id": "competition", "label": "Présence grand réseau", "unit": "bool", "priority": "P0",
     "description": "Alerte si réseau fort déjà implanté.",
     "source_priority": ["corporate", "commercial"]},
    {"metric_id": "franchise_brand_count", "theme_id": "competition", "label": "Franchises présentes", "unit": "marques", "priority": "P1",
     "description": "Nombre de marques nationales sur la zone.",
     "source_priority": ["corporate", "commercial"]},
    {"metric_id": "association_competitor_count", "theme_id": "competition", "label": "Associations (ADMR, UNA, etc.)", "unit": "acteurs", "priority": "P1",
     "description": "Acteurs associatifs - concurrence directe sur seniors.",
     "source_priority": ["semi_official", "official_local"]},
    {"metric_id": "ccas_presence_flag", "theme_id": "competition", "label": "Présence CCAS local", "unit": "bool", "priority": "P1",
     "description": "Concurrence publique communale.",
     "source_priority": ["official_local"]},
    {"metric_id": "recent_openings_2y", "theme_id": "competition", "label": "Ouvertures récentes (2 ans)", "unit": "acteurs", "priority": "P1",
     "description": "Signal de dynamique concurrentielle.",
     "source_priority": ["commercial", "press"]},

    # === PRICING ===
    {"metric_id": "avg_hourly_price_cleaning", "theme_id": "pricing", "label": "Prix horaire ménage", "unit": "EUR/h", "priority": "P1",
     "description": "Benchmark monétisation ménage.",
     "source_priority": ["commercial", "corporate"]},
    {"metric_id": "avg_hourly_price_care", "theme_id": "pricing", "label": "Prix horaire aide à domicile", "unit": "EUR/h", "priority": "P1",
     "description": "Benchmark monétisation seniors.",
     "source_priority": ["commercial", "corporate"]},
    {"metric_id": "regulated_saad_rate", "theme_id": "pricing", "label": "Tarif SAAD conventionné", "unit": "EUR/h", "priority": "P1",
     "description": "Plafond tarif réglementé local.",
     "source_priority": ["official_regional", "official_local"]},

    # === MOBILITY / OPERATIONS ===
    {"metric_id": "travel_time_spread", "theme_id": "operations", "label": "Dispersion temps de trajet", "unit": "min", "priority": "P1",
     "description": "Efficacité opérationnelle.",
     "source_priority": ["official_local", "semi_official", "commercial"]},
    {"metric_id": "parking_constraint_index", "theme_id": "operations", "label": "Contrainte stationnement", "unit": "indice", "priority": "P2",
     "description": "Complexité opérationnelle urbaine.",
     "source_priority": ["official_local", "semi_official"]},
    {"metric_id": "car_dependency_share", "theme_id": "operations", "label": "Dépendance automobile", "unit": "%", "priority": "P1",
     "description": "Part actifs en voiture - impact recrutement.",
     "source_priority": ["official_national", "official_local"]},
    {"metric_id": "rush_hour_penalty", "theme_id": "operations", "label": "Pénalité heures de pointe", "unit": "min", "priority": "P2",
     "description": "Allongement trajets matin/soir.",
     "source_priority": ["official_local", "commercial"]},

    # === TOURISM / SEASONALITY ===
    {"metric_id": "tourism_overnight_stays", "theme_id": "tourism", "label": "Nuitées touristiques annuelles", "unit": "nuitées", "priority": "P1",
     "description": "Volume tourisme.",
     "source_priority": ["official_regional", "official_local"]},
    {"metric_id": "tourism_seasonality_index", "theme_id": "tourism", "label": "Indice saisonnalité", "unit": "indice", "priority": "P1",
     "description": "Ratio haute saison / basse saison.",
     "source_priority": ["official_regional", "official_local"]},
    {"metric_id": "seasonal_revenue_multiplier", "theme_id": "tourism", "label": "Coefficient CA été/hiver", "unit": "x", "priority": "P1",
     "description": "Impact saisonnier estimé sur CA.",
     "source_priority": ["semi_official", "corporate"]},

    # === REGULATION ===
    {"metric_id": "regulatory_barrier_level", "theme_id": "regulation", "label": "Barrière réglementaire", "unit": "indice", "priority": "P0",
     "description": "Complexité autorisation / agrément.",
     "source_priority": ["official_national", "official_regional"]},
    {"metric_id": "public_aid_coverage", "theme_id": "regulation", "label": "Couverture aides publiques", "unit": "indice", "priority": "P1",
     "description": "Solvabilisation publique de la demande.",
     "source_priority": ["official_national", "official_regional", "official_local"]},
    {"metric_id": "saad_authorization_required", "theme_id": "regulation", "label": "Autorisation SAAD requise", "unit": "bool", "priority": "P0",
     "description": "Obligation d'autorisation dépendance.",
     "source_priority": ["official_regional"]},
    {"metric_id": "apa_hourly_rate", "theme_id": "regulation", "label": "Tarif horaire APA local", "unit": "EUR/h", "priority": "P1",
     "description": "Tarif aide personnalisée autonomie.",
     "source_priority": ["official_regional"]},

    # === BUSINESS CASE ===
    {"metric_id": "estimated_initial_investment", "theme_id": "business_case", "label": "Investissement initial", "unit": "EUR", "priority": "P0",
     "description": "Faisabilité financière d'ouverture.",
     "source_priority": ["corporate", "commercial", "semi_official"],
     "lovable_optional": True,
     "lovable_default_visible": False},
    {"metric_id": "estimated_monthly_fixed_costs", "theme_id": "business_case", "label": "Charges fixes mensuelles", "unit": "EUR/mois", "priority": "P1",
     "description": "Point mort local.",
     "source_priority": ["corporate", "commercial", "semi_official"],
     "lovable_optional": True,
     "lovable_default_visible": False},
    {"metric_id": "recurring_revenue_share_potential", "theme_id": "business_case", "label": "Part CA récurrent", "unit": "%", "priority": "P0",
     "description": "Qualité structurelle du mix.",
     "source_priority": ["official_national", "commercial", "corporate"]},
    {"metric_id": "premium_customer_potential", "theme_id": "business_case", "label": "Potentiel clientèle premium", "unit": "indice", "priority": "P0",
     "description": "Capacité du territoire à supporter une offre premium.",
     "source_priority": ["official_national", "commercial", "semi_official"]},
    {"metric_id": "franchise_entry_fee", "theme_id": "business_case", "label": "Droit d'entrée franchise", "unit": "EUR", "priority": "P2",
     "description": "Coût d'entrée réseau (achat franchise).",
     "source_priority": ["corporate"],
     "lovable_optional": True,
     "lovable_default_visible": False,
     "franchise_purchase_cost": True},
    {"metric_id": "franchise_royalty_rate", "theme_id": "business_case", "label": "Redevance franchise", "unit": "%", "priority": "P2",
     "description": "Redevance sur CA (achat franchise).",
     "source_priority": ["corporate"],
     "lovable_optional": True,
     "lovable_default_visible": False,
     "franchise_purchase_cost": True},
]


KPI_BY_ID = {item["metric_id"]: item for item in KPI_CATALOG}


THEME_LABELS = {
    "demography": "Démographie",
    "target_segments": "Segments cibles",
    "employment": "Emploi & RH",
    "income_housing": "Revenus & habitat",
    "real_estate": "Immobilier (prix m² / loyer)",
    "microzones": "Quartiers / rues / routes",
    "competition": "Concurrence",
    "pricing": "Pricing",
    "operations": "Opérations & mobilité",
    "tourism": "Tourisme & saisonnalité",
    "regulation": "Réglementation",
    "business_case": "Business case",
}
