SECTION_SLOT_CONTRACTS = {
    "cover": {
        "headline": "str",
        "subheadline": "str",
        "territory_label": "str",
        "study_date": "date",
        "hero_kpis": "list[3..6]",
        "decision_teaser": "str",
    },
    "executive_summary": {
        "headline": "str",
        "summary_bullets": "list[3..5]",
        "top_kpis": "list[4..8]",
        "main_risks": "list[2..4]",
        "key_decisions": "list[2..4]",
    },
    "methodology_sources": {
        "headline": "str",
        "method_steps": "list[4..7]",
        "source_groups": "list[3..6]",
        "coverage_note": "str",
        "confidence_note": "str",
    },
    "market_scorecard": {
        "headline": "str",
        "global_score": "number",
        "sub_scores": "list[7]",
        "verdict_label": "str",
        "score_explanation": "list[3..5]",
    },
    "demographics": {
        "headline": "str",
        "summary_bullets": "list[3..5]",
        "kpis": "list[3..6]",
        "comparison_rows": "list[4..8]",
        "chart_series": "list[1..2]",
        "confidence_grade": "str",
    },
    "target_segments": {
        "headline": "str",
        "segment_cards": "list[3..4]",
        "segment_takeaways": "list[3..5]",
        "priority_segment": "str",
        "confidence_grade": "str",
    },
    "employment_talent": {
        "headline": "str",
        "summary_bullets": "list[3..5]",
        "kpis": "list[3..6]",
        "risk_flags": "list[2..4]",
        "recruitment_outlook": "str",
        "confidence_grade": "str",
    },
    "income_housing": {
        "headline": "str",
        "summary_bullets": "list[3..5]",
        "kpis": "list[4..8]",
        "comparison_rows": "list[4..8]",
        "premium_signal": "str",
        "confidence_grade": "str",
    },
    "real_estate": {
        "headline": "str",
        "summary_bullets": "list[3..5]",
        "price_kpis": "list[4..6]",
        "premium_zones": "list[2..5]",
        "price_dynamics_note": "str",
        "confidence_grade": "str",
    },
    "microzones": {
        "headline": "str",
        "summary_bullets": "list[3..5]",
        "neighborhood_rows": "list[4..10]",
        "key_streets": "list[3..8]",
        "traffic_axes": "list[2..5]",
        "transit_lines": "list[2..5]",
        "priority_targets": "list[2..4]",
        "confidence_grade": "str",
    },
    "competition_mapping": {
        "headline": "str",
        "market_takeaway": "str",
        "competitor_rows": "list[8..15]",
        "top_competitors": "list[3..5]",
        "alerts": "list[2..4]",
        "confidence_grade": "str",
    },
    "regulation_feasibility": {
        "headline": "str",
        "summary_bullets": "list[3..5]",
        "constraint_rows": "list[3..6]",
        "aid_rows": "list[2..5]",
        "compliance_takeaway": "str",
        "confidence_grade": "str",
    },
    "swot": {
        "headline": "str",
        "strengths": "list[5..8]",
        "weaknesses": "list[5..8]",
        "opportunities": "list[5..8]",
        "threats": "list[5..8]",
        "strategic_takeaway": "str",
    },
    "verdict": {
        "headline": "str",
        "decision": "str",
        "decision_label": "str",
        "rationale_bullets": "list[3..5]",
        "conditions": "list[0..3]",
        "next_step": "str",
        "confidence_grade": "str",
    },
    "action_plan": {
        "headline": "str",
        "horizon_30_days": "list[3..5]",
        "horizon_60_days": "list[3..5]",
        "horizon_90_days": "list[3..5]",
        "owner_roles": "list[3..6]",
        "success_checks": "list[3..5]",
    },
}


SECTION_EXPECTED_KPIS = {
    "cover": [
        "population_total",
        "seniors_60_plus_share",
        "competitor_count_15min",
        "real_estate_price_house_m2",
    ],
    "executive_summary": [
        "population_total",
        "seniors_60_plus_share",
        "unemployment_rate",
        "median_income",
        "real_estate_price_house_m2",
        "competitor_count_15min",
    ],
    "methodology_sources": [],
    "market_scorecard": [],
    "demographics": [
        "population_total",
        "population_growth_5y",
        "density_population",
    ],
    "target_segments": [
        "seniors_60_plus_share",
        "seniors_75_plus_share",
        "households_with_children_share",
        "single_senior_households",
        "dependency_ratio_apa",
    ],
    "employment_talent": [
        "unemployment_rate",
        "care_worker_pool",
        "jobseekers_service_sector",
        "car_dependency_share",
    ],
    "income_housing": [
        "median_income",
        "taxable_households_share",
        "home_ownership_share",
        "tenants_share",
        "secondary_residences_share",
        "houses_vs_apartments_share",
        "avg_house_surface",
    ],
    "real_estate": [
        "real_estate_price_house_m2",
        "real_estate_price_apartment_m2",
        "rental_price_m2",
        "real_estate_avg_transaction",
        "real_estate_price_growth_5y",
        "real_estate_premium_zone_share",
    ],
    "microzones": [
        "neighborhood_count",
        "premium_neighborhoods_count",
        "key_streets_count",
        "main_traffic_axes",
        "transit_lines_count",
    ],
    "competition_mapping": [
        "competitor_count_15min",
        "competitor_count_30min",
        "top_competitor_density",
        "brand_presence_flag",
        "franchise_brand_count",
        "association_competitor_count",
        "ccas_presence_flag",
        "recent_openings_2y",
        "avg_hourly_price_cleaning",
        "avg_hourly_price_care",
    ],
    "regulation_feasibility": [
        "regulatory_barrier_level",
        "public_aid_coverage",
        "saad_authorization_required",
        "apa_hourly_rate",
    ],
    "swot": [
        "population_total",
        "seniors_60_plus_share",
        "unemployment_rate",
        "median_income",
        "real_estate_price_house_m2",
        "competitor_count_15min",
        "regulatory_barrier_level",
    ],
    "verdict": [],
    "action_plan": [],
}
